version: '3'

services:
  influxdb:
    image: influxdb:1.8
    container_name: sanbox-influxdb
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    ports:
      - "8086:8086"

  telegraf:
    image: telegraf:1.27-alpine
    container_name: sanbox-telegraf
    restart: always
    privileged: true
    depends_on:
      - influxdb
    environment:
      HOSTNAME: telegraf-getting-started
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /etc:/hostfs/etc:ro
      - /var/lib/docker:/var/lib/docker:ro
    links:
      - influxdb

  chronograf:
    image: chronograf:latest
    container_name: sanbox-chronograf
    depends_on:
      - influxdb
      - telegraf
    ports:
      - "8888:8888"
    links:
      - influxdb